AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  CoreStackName:
    Type: String
    Description: Core stack name
    Default: prod-core
  ECSStackName:
    Type: String
    Description: Core stack name
    Default: prod-ecs-web
  Environment:
    Type: String
    Description: Environment
    Default: production

Resources:

  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 16
      MinCapacity: 2
      ResourceId:
        Fn::Join: [ '', [ 'service/', 'Fn::ImportValue': { 'Fn::Sub': '${CoreStackName}-WebCluster' }, '/', 'Fn::ImportValue': { 'Fn::Sub': '${ECSStackName}-ECSWebService' } ] ]
      RoleARN:
        Fn::ImportValue: !Sub "${CoreStackName}-ECSRoleEcsInstanceArn"
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  ScaleOutPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Join [ '', [ 'scale-out-web-', !Ref Environment ] ]
      PolicyType: StepScaling
      ScalingTargetId: !Ref ScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 180
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            ScalingAdjustment: 2

  AlarmOsirocomWebOverLoad:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref ScaleOutPolicy
      AlarmDescription:
        Fn::Join: [ '', [ 'Cluster ', 'Fn::ImportValue': { 'Fn::Sub': '${CoreStackName}-WebCluster' }, ' overload' ] ]
      AlarmName:
        Fn::Join: [ '', [ 'Fn::ImportValue': { 'Fn::Sub': '${CoreStackName}-WebCluster' }, '-overload' ] ]
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: ClusterName
          Value:
            Fn::ImportValue:
              Fn::Sub: '${CoreStackName}-WebCluster'
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Period: 60
      Statistic: Average
      Threshold: 70
      TreatMissingData: breaching
